[project]
name = "flood"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.ruff]
line-length = 98
indent-width = 4

[tool.ruff.lint]
select = ["E", "F", "B"]
ignore = []
